import { Language } from "./translations";

export const extraTranslations: Record<Language, any> = {
  en: {
    "ind.1.name": "Healthcare",
    "ind.1.desc": "Advanced digital health ecosystems and AI-driven diagnostics for modern patient care.",
    "ind.2.name": "E-Commerce",
    "ind.2.desc": "Next-generation retail solutions with autonomous intelligence and personalized shopping.",
    "ind.3.name": "Education",
    "ind.3.desc": "Scalable platforms for global learning, powered by interactive and immersive technologies.",
    "ind.4.name": "Real Estate",
    "ind.4.desc": "Immersive property solutions and architectural visualizations for future-ready developments.",
    "ind.5.name": "Finance",
    "ind.5.desc": "Secure, data-driven economic frameworks and fintech innovations for global markets.",
    "ind.6.name": "Logistics",
    "ind.6.desc": "Optimized supply chains and autonomous delivery systems through neural network integration.",
    
    "tst.1.text": "Softcr8ors built our entire e-commerce platform from scratch. The design is stunning and conversions are up 40% since launch.",
    "tst.1.role": "CEO, LuxeCart",
    "tst.2.text": "Their UI/UX team transformed our app's experience. User retention doubled within the first month after the redesign.",
    "tst.2.role": "Product Lead, Evergreen",
    "tst.3.text": "The brand identity they created for us is incredible. We've received so many compliments from clients and partners.",
    "tst.3.role": "Founder, Atlas Studios",
    "tst.4.text": "The video production quality is truly cinematic. Our brand reel generated over 500K views in the first week.",
    "tst.4.role": "CMO, NovaBrands",
    "tst.5.text": "They delivered our custom CRM software ahead of schedule and it works flawlessly. Highly recommend the team.",
    "tst.5.role": "COO, TechFlow",
    "tst.6.text": "Softcr8ors redesigned our entire digital presence. The website is fast, beautiful, and converts like nothing before.",
    "tst.6.role": "Director, Q Global",
    "tst.7.text": "Professional, creative, and technically brilliant. They turned our rough ideas into a polished mobile app in 8 weeks.",
    "tst.7.role": "Co-Founder, Appify",
    "tst.8.text": "Best agency we've worked with. Their audio and video editing elevated our content to a whole new professional level.",
    "tst.8.role": "Head of Marketing, CreatorHub",

    "srv.1": "Remote IT Resources",
    "srv.2": "Custom Software Development",
    "srv.3": "Web Development",
    "srv.4": "Mobile App Development",
    "srv.5": "AR / VR",
    "srv.6": "Gaming",
    "srv.7": "Cyber Security",
    "srv.8": "Other IT Services",

    "team.1.role": "Python AI Engineer",
    "team.2.role": "MERN Stack Developer",
    "team.3.role": "Next.js Developer",
    "team.4.role": "WordPress Developer",
    "team.5.role": "Business Developer",
    "team.6.role": "UI/UX Designer",
    "team.7.role": "Full Stack Developer",

    "ftr.desc": "Softcr8ors empowers fast-growing companies with state-of-the-art web engineering, custom software solutions, and production-ready AI platforms that scale.",
    "ftr.srv.1": "Web Engineering",
    "ftr.srv.2": "Custom Software",
    "ftr.srv.3": "Mobile Innovation",
    "ftr.srv.4": "SaaS Platforms",
    "ftr.srv.5": "Gen AI Content",
    "ftr.srv.6": "Intelligence AI",
    "ftr.srv.7": "UI/UX Design",
    "ftr.srv.8": "Technical SEO",
    
    "ftr.nav.1": "About",
    "ftr.nav.2": "Services",
    "ftr.nav.3": "Testimonials",
    "ftr.nav.4": "Contact",

    "ftr.cnt.1": "Start a Project",
    "ftr.cnt.2": "Book a Demo",
    
    "ftr.pol.1": "Privacy Policy",
    "ftr.pol.2": "Terms of Service",
    "ftr.pol.3": "Cookies Settings",
    "ftr.copy": "© 2026 Softcr8ors. All rights reserved."
  },
  ur: {
    "ind.1.name": "ہیلتھ کیئر",
    "ind.1.desc": "جدید ڈیجیٹل ہیلتھ ایکو سسٹم اور جدید مریضوں کی دیکھ بھال کے لیے AI تشخیص۔",
    "ind.2.name": "ای کامرس",
    "ind.2.desc": "خودمختار ذہانت اور ذاتی خریداری کے ساتھ اگلی نسل کے ریٹیل حل۔",
    "ind.3.name": "تعلیم",
    "ind.3.desc": "عالمی تعلیم کے لیے اسکیل ایبل پلیٹ فارمز، انٹرایکٹو ٹیکنالوجیز سے لیس۔",
    "ind.4.name": "ریئل اسٹیٹ",
    "ind.4.desc": "مستقبل کے لیے تیار ترقی کے لیے پراپرٹی کے حل اور آرکیٹیکچرل ویژولائزیشن۔",
    "ind.5.name": "مالیات",
    "ind.5.desc": "عالمی منڈیوں کے لیے محفوظ، ڈیٹا پر مبنی اقتصادی فریم ورک اور فنٹیک اختراعات۔",
    "ind.6.name": "لاجسٹکس",
    "ind.6.desc": "بہتر سپلائی چینز اور نیورل نیٹ ورک انضمام کے ذریعے خود مختار ترسیل کے نظام۔",
    
    "tst.1.text": "Softcr8ors نے شروع سے ہمارا پورا ای کامرس پلیٹ فارم بنایا۔ ڈیزائن شاندار ہے اور لانچ کے بعد سے تبادلوں میں 40% اضافہ ہوا ہے۔",
    "tst.1.role": "سی ای او، LuxeCart",
    "tst.2.text": "ان کی UI/UX ٹیم نے ہماری ایپ کا تجربہ بدل دیا۔ ری ڈیزائن کے بعد پہلے ہی مہینے میں صارفین کی برقراری دوگنی ہو گئی۔",
    "tst.2.role": "پروڈکٹ لیڈ، Evergreen",
    "tst.3.text": "انھوں نے ہمارے لیے جو برانڈ شناخت بنائی ہے وہ ناقابل یقین ہے۔ ہمیں کلائنٹس اور شراکت داروں سے بہت سی تعریفیں ملی ہیں۔",
    "tst.3.role": "بانی، Atlas Studios",
    "tst.4.text": "ویڈیو پروڈکشن کا معیار واقعی شاندار ہے۔ ہمارے برانڈ ریل نے پہلے ہفتے میں 500K سے زیادہ ملاحظات حاصل کیے۔",
    "tst.4.role": "سی ایم او، NovaBrands",
    "tst.5.text": "انھوں نے ہمارا کسٹم CRM سافٹ ویئر شیڈول سے پہلے ڈیلیور کیا اور یہ بے عیب کام کرتا ہے۔ انتہائی سفارش کی جاتی ہے۔",
    "tst.5.role": "سی او او، TechFlow",
    "tst.6.text": "Softcr8ors نے ہماری پوری ڈیجیٹل موجودگی کو دوبارہ ڈیزائن کیا۔ ویب سائٹ تیز، خوبصورت اور پہلے سے بہتر ہے۔",
    "tst.6.role": "ڈائریکٹر، Q Global",
    "tst.7.text": "پیشہ ور، تخلیقی، اور تکنیکی طور پر شاندار۔ انھوں نے ہمارے خیالات کو 8 ہفتوں میں ایک پالش موبائل ایپ میں بدل دیا۔",
    "tst.7.role": "شریک بانی، Appify",
    "tst.8.text": "بہترین ایجنسی جس کے ساتھ ہم نے کام کیا ہے۔ ان کی آڈیو اور ویڈیو ایڈیٹنگ نے ہمارے مواد کو ایک نئی پیشہ ورانہ سطح پر پہنچا دیا۔",
    "tst.8.role": "مارکیٹنگ ہیڈ، CreatorHub",

    "srv.1": "ریموٹ آئی ٹی وسائل",
    "srv.2": "کسٹم سافٹ ویئر ڈیولپمنٹ",
    "srv.3": "ویب ڈیولپمنٹ",
    "srv.4": "موبائل ایپ ڈیولپمنٹ",
    "srv.5": "اے آر / وی آر",
    "srv.6": "گیمنگ",
    "srv.7": "سائبر سیکیورٹی",
    "srv.8": "دیگر آئی ٹی سروسز",

    "team.1.role": "پائتھون اے آئی انجینئر",
    "team.2.role": "MERN اسٹیک ڈیولپر",
    "team.3.role": "Next.js ڈیولپر",
    "team.4.role": "ورڈپریس ڈیولپر",
    "team.5.role": "بزنس ڈیولپر",
    "team.6.role": "یو آئی / یو ایکس ڈیزائنر",
    "team.7.role": "فل اسٹیک ڈیولپر",

    "ftr.desc": "Softcr8ors تیزی سے ترقی کرنے والی کمپنیوں کو جدید ویب انجینئرنگ، کسٹم سافٹ ویئر حل اور پروڈکشن ریڈی AI پلیٹ فارمز کے ساتھ بااختیار بناتا ہے۔",
    "ftr.srv.1": "ویب انجینئرنگ",
    "ftr.srv.2": "کسٹم سافٹ ویئر",
    "ftr.srv.3": "موبائل انوویشن",
    "ftr.srv.4": "SaaS پلیٹ فارمز",
    "ftr.srv.5": "Gen AI کونٹینٹ",
    "ftr.srv.6": "انٹیلیجنس AI",
    "ftr.srv.7": "UI/UX ڈیزائن",
    "ftr.srv.8": "تکنیکی SEO",
    
    "ftr.nav.1": "ہمارے بارے میں",
    "ftr.nav.2": "خدمات",
    "ftr.nav.3": "ٹیسٹیمونیلز",
    "ftr.nav.4": "رابطہ کریں",

    "ftr.cnt.1": "پروجیکٹ شروع کریں",
    "ftr.cnt.2": "ڈیمو بک کریں",
    
    "ftr.pol.1": "پرائیویسی پالیسی",
    "ftr.pol.2": "سروس کی شرائط",
    "ftr.pol.3": "کوکیز کی ترتیبات",
    "ftr.copy": "© 2026 Softcr8ors۔ جملہ حقوق محفوظ ہیں۔"
  },
  ar: {
    "ind.1.name": "الرعاية الصحية",
    "ind.1.desc": "أنظمة بيئية رقمية متقدمة للصحة وتشخيصات مدفوعة بالذكاء الاصطناعي لرعاية المرضى الحديثة.",
    "ind.2.name": "التجارة الإلكترونية",
    "ind.2.desc": "حلول التجزئة من الجيل القادم مع الذكاء المستقل والتسوق المخصص.",
    "ind.3.name": "التعليم",
    "ind.3.desc": "منصات قابلة للتطوير للتعلم العالمي، مدعومة بالتقنيات التفاعلية والغامرة.",
    "ind.4.name": "العقارات",
    "ind.4.desc": "حلول عقارية غامرة وتصورات معمارية للتطورات المستقبلية.",
    "ind.5.name": "المالية",
    "ind.5.desc": "أطر اقتصادية آمنة ومدفوعة بالبيانات وابتكارات التكنولوجيا المالية للأسواق العالمية.",
    "ind.6.name": "الخدمات اللوجستية",
    "ind.6.desc": "سلاسل التوريد المحسنة وأنظمة التوصيل المستقلة من خلال تكامل الشبكة العصبية.",
    
    "tst.1.text": "قامت Softcr8ors ببناء منصة التجارة الإلكترونية الخاصة بنا بالكامل من الصفر. التصميم مذهل وزادت التحويلات بنسبة 40٪ منذ الإطلاق.",
    "tst.1.role": "الرئيس التنفيذي ، LuxeCart",
    "tst.2.text": "فريق UI/UX الخاص بهم حول تجربة تطبيقنا. تضاعف الاحتفاظ بالمستخدمين خلال الشهر الأول بعد إعادة التصميم.",
    "tst.2.role": "قائد المنتج ، Evergreen",
    "tst.3.text": "هوية العلامة التجارية التي أنشأوها لنا لا تصدق. لقد تلقينا العديد من الإطراءات من العملاء والشركاء.",
    "tst.3.role": "المؤسس ، Atlas Studios",
    "tst.4.text": "جودة إنتاج الفيديو سينمائية حقًا. حصدت بكرة علامتنا التجارية أكثر من 500 ألف مشاهدة في الأسبوع الأول.",
    "tst.4.role": "رئيس التسويق ، NovaBrands",
    "tst.5.text": "لقد سلموا برنامج CRM المخصص لدينا قبل الموعد المحدد ويعمل بشكل لا تشوبه شائبة. نوصي بشدة بالفريق.",
    "tst.5.role": "مدير العمليات ، TechFlow",
    "tst.6.text": "قامت Softcr8ors بإعادة تصميم تواجدنا الرقمي بالكامل. الموقع سريع وجميل ويحول بشكل لم يسبق له مثيل.",
    "tst.6.role": "المدير ، Q Global",
    "tst.7.text": "محترف، مبدع، ورائع تقنيًا. لقد حولوا أفكارنا الأولية إلى تطبيق جوال مصقول في 8 أسابيع.",
    "tst.7.role": "شريك مؤسس ، Appify",
    "tst.8.text": "أفضل وكالة عملنا معها. أدى تحرير الصوت والفيديو إلى رفع المحتوى الخاص بنا إلى مستوى احترافي جديد تمامًا.",
    "tst.8.role": "رئيس التسويق ، CreatorHub",

    "srv.1": "موارد تقنية المعلومات عن بعد",
    "srv.2": "تطوير البرمجيات المخصصة",
    "srv.3": "تطوير الويب",
    "srv.4": "تطوير تطبيقات الجوال",
    "srv.5": "الواقع المعزز / الافتراضي",
    "srv.6": "الألعاب",
    "srv.7": "الأمن السيبراني",
    "srv.8": "خدمات تكنولوجيا المعلومات الأخرى",

    "team.1.role": "مهندس ذكاء اصطناعي (بايثون)",
    "team.2.role": "مطور MERN Stack",
    "team.3.role": "مطور Next.js",
    "team.4.role": "مطور ووردبريس",
    "team.5.role": "مطور أعمال",
    "team.6.role": "مصمم UI/UX",
    "team.7.role": "مطور Full Stack",

    "ftr.desc": "تعمل Softcr8ors على تمكين الشركات سريعة النمو من خلال هندسة الويب المتطورة وحلول البرامج المخصصة ومنصات الذكاء الاصطناعي الجاهزة للإنتاج والتي تتوسع.",
    "ftr.srv.1": "هندسة الويب",
    "ftr.srv.2": "البرامج المخصصة",
    "ftr.srv.3": "ابتكار الهاتف المحمول",
    "ftr.srv.4": "منصات SaaS",
    "ftr.srv.5": "محتوى الذكاء الاصطناعي",
    "ftr.srv.6": "الذكاء الاصطناعي الذكي",
    "ftr.srv.7": "تصميم UI/UX",
    "ftr.srv.8": "تحسين محركات البحث التقني",
    
    "ftr.nav.1": "معلومات عنا",
    "ftr.nav.2": "الخدمات",
    "ftr.nav.3": "الشهادات",
    "ftr.nav.4": "اتصل بنا",

    "ftr.cnt.1": "ابدأ مشروعًا",
    "ftr.cnt.2": "احجز عرضًا توضيحيًا",
    
    "ftr.pol.1": "سياسة الخصوصية",
    "ftr.pol.2": "شروط الخدمة",
    "ftr.pol.3": "إعدادات ملفات تعريف الارتباط",
    "ftr.copy": "© 2026 Softcr8ors. جميع الحقوق محفوظة."
  },
  es: {
    "ind.1.name": "Cuidado de la salud",
    "ind.1.desc": "Ecosistemas avanzados de salud digital y diagnósticos impulsados por IA para la atención moderna del paciente.",
    "ind.2.name": "Comercio Electrónico",
    "ind.2.desc": "Soluciones minoristas de próxima generación con inteligencia autónoma y compras personalizadas.",
    "ind.3.name": "Educación",
    "ind.3.desc": "Plataformas escalables para el aprendizaje global, impulsadas por tecnologías interactivas e inmersivas.",
    "ind.4.name": "Bienes Raíces",
    "ind.4.desc": "Soluciones inmobiliarias inmersivas y visualizaciones arquitectónicas para desarrollos preparados para el futuro.",
    "ind.5.name": "Finanzas",
    "ind.5.desc": "Marcos económicos seguros basados en datos e innovaciones fintech para mercados globales.",
    "ind.6.name": "Logística",
    "ind.6.desc": "Cadenas de suministro optimizadas y sistemas de entrega autónomos mediante integración de redes neuronales.",
    
    "tst.1.text": "Softcr8ors construyó toda nuestra plataforma de comercio electrónico desde cero. El diseño es impresionante y las conversiones han aumentado un 40%.",
    "tst.1.role": "CEO, LuxeCart",
    "tst.2.text": "Su equipo de UI/UX transformó la experiencia de nuestra aplicación. La retención de usuarios se duplicó en el primer mes.",
    "tst.2.role": "Líder de Producto, Evergreen",
    "tst.3.text": "La identidad de marca que crearon para nosotros es increíble. Hemos recibido muchos elogios de clientes y socios.",
    "tst.3.role": "Fundador, Atlas Studios",
    "tst.4.text": "La calidad de producción de video es verdaderamente cinematográfica. Nuestro carrete de marca generó más de 500K vistas.",
    "tst.4.role": "CMO, NovaBrands",
    "tst.5.text": "Entregaron nuestro software CRM personalizado antes de lo previsto y funciona sin problemas. Recomiendo encarecidamente al equipo.",
    "tst.5.role": "COO, TechFlow",
    "tst.6.text": "Softcr8ors rediseñó toda nuestra presencia digital. El sitio web es rápido, hermoso y convierte como nunca antes.",
    "tst.6.role": "Director, Q Global",
    "tst.7.text": "Profesional, creativo y técnicamente brillante. Convirtieron nuestras ideas en una aplicación móvil pulida en 8 semanas.",
    "tst.7.role": "Cofundador, Appify",
    "tst.8.text": "La mejor agencia con la que hemos trabajado. Su edición de audio y video elevó nuestro contenido a un nuevo nivel profesional.",
    "tst.8.role": "Jefe de Marketing, CreatorHub",

    "srv.1": "Recursos de TI Remotos",
    "srv.2": "Desarrollo de Software a Medida",
    "srv.3": "Desarrollo Web",
    "srv.4": "Desarrollo de Aplicaciones Móviles",
    "srv.5": "Realidad Aumentada / Virtual",
    "srv.6": "Juegos",
    "srv.7": "Ciberseguridad",
    "srv.8": "Otros Servicios de TI",

    "team.1.role": "Ingeniero de IA en Python",
    "team.2.role": "Desarrollador Stack MERN",
    "team.3.role": "Desarrollador Next.js",
    "team.4.role": "Desarrollador WordPress",
    "team.5.role": "Desarrollador de Negocios",
    "team.6.role": "Diseñador UI/UX",
    "team.7.role": "Desarrollador Full Stack",

    "ftr.desc": "Softcr8ors capacita a empresas de rápido crecimiento con ingeniería web de vanguardia, soluciones de software personalizadas y plataformas de IA.",
    "ftr.srv.1": "Ingeniería Web",
    "ftr.srv.2": "Software a Medida",
    "ftr.srv.3": "Innovación Móvil",
    "ftr.srv.4": "Plataformas SaaS",
    "ftr.srv.5": "Contenido de IA Gen",
    "ftr.srv.6": "IA de Inteligencia",
    "ftr.srv.7": "Diseño UI/UX",
    "ftr.srv.8": "SEO Técnico",
    
    "ftr.nav.1": "Acerca de",
    "ftr.nav.2": "Servicios",
    "ftr.nav.3": "Testimonios",
    "ftr.nav.4": "Contacto",

    "ftr.cnt.1": "Iniciar un Proyecto",
    "ftr.cnt.2": "Reservar una Demostración",
    
    "ftr.pol.1": "Política de Privacidad",
    "ftr.pol.2": "Términos de Servicio",
    "ftr.pol.3": "Configuración de Cookies",
    "ftr.copy": "© 2026 Softcr8ors. Todos los derechos reservados."
  },
  fr: {
    "ind.1.name": "Soins de santé",
    "ind.1.desc": "Écosystèmes de santé numériques avancés et diagnostics par IA pour les soins modernes aux patients.",
    "ind.2.name": "E-Commerce",
    "ind.2.desc": "Solutions de vente au détail de nouvelle génération avec intelligence autonome et achats personnalisés.",
    "ind.3.name": "Éducation",
    "ind.3.desc": "Plateformes évolutives pour l'apprentissage mondial, optimisées par des technologies interactives et immersives.",
    "ind.4.name": "Immobilier",
    "ind.4.desc": "Solutions immobilières immersives et visualisations architecturales pour des développements prêts pour l'avenir.",
    "ind.5.name": "Finance",
    "ind.5.desc": "Cadres économiques sécurisés et axés sur les données et innovations fintech pour les marchés mondiaux.",
    "ind.6.name": "Logistique",
    "ind.6.desc": "Chaînes d'approvisionnement optimisées et systèmes de livraison autonomes grâce à l'intégration de réseaux de neurones.",
    
    "tst.1.text": "Softcr8ors a construit toute notre plateforme de commerce électronique à partir de zéro. Le design est magnifique et les conversions ont augmenté de 40 %.",
    "tst.1.role": "PDG, LuxeCart",
    "tst.2.text": "Leur équipe UI/UX a transformé l'expérience de notre application. La rétention des utilisateurs a doublé au cours du premier mois.",
    "tst.2.role": "Chef de Produit, Evergreen",
    "tst.3.text": "L'identité de marque qu'ils ont créée pour nous est incroyable. Nous avons reçu tellement de compliments de la part des clients.",
    "tst.3.role": "Fondateur, Atlas Studios",
    "tst.4.text": "La qualité de production vidéo est vraiment cinématographique. Notre bobine de marque a généré plus de 500 000 vues.",
    "tst.4.role": "Directeur Marketing, NovaBrands",
    "tst.5.text": "Ils ont livré notre logiciel CRM personnalisé en avance sur le calendrier et il fonctionne parfaitement.",
    "tst.5.role": "Directeur de l'Exploitation, TechFlow",
    "tst.6.text": "Softcr8ors a repensé l'ensemble de notre présence numérique. Le site Web est rapide, magnifique et convertit comme jamais auparavant.",
    "tst.6.role": "Directeur, Q Global",
    "tst.7.text": "Professionnel, créatif et techniquement brillant. Ils ont transformé nos idées approximatives en une application mobile soignée en 8 semaines.",
    "tst.7.role": "Co-fondateur, Appify",
    "tst.8.text": "Meilleure agence avec laquelle nous avons travaillé. Leur montage audio et vidéo a élevé notre contenu à un tout autre niveau.",
    "tst.8.role": "Responsable du Marketing, CreatorHub",

    "srv.1": "Ressources Informatiques à Distance",
    "srv.2": "Développement Logiciel Sur Mesure",
    "srv.3": "Développement Web",
    "srv.4": "Développement d'Applications Mobiles",
    "srv.5": "Réalité Augmentée / Virtuelle",
    "srv.6": "Jeux",
    "srv.7": "Cybersécurité",
    "srv.8": "Autres Services Informatiques",

    "team.1.role": "Ingénieur IA Python",
    "team.2.role": "Développeur Stack MERN",
    "team.3.role": "Développeur Next.js",
    "team.4.role": "Développeur WordPress",
    "team.5.role": "Développeur Commercial",
    "team.6.role": "Designer UI/UX",
    "team.7.role": "Développeur Full Stack",

    "ftr.desc": "Softcr8ors donne aux entreprises à croissance rapide des moyens avec une ingénierie Web de pointe, des solutions logicielles personnalisées et des plateformes d'IA.",
    "ftr.srv.1": "Ingénierie Web",
    "ftr.srv.2": "Logiciel Sur Mesure",
    "ftr.srv.3": "Innovation Mobile",
    "ftr.srv.4": "Plateformes SaaS",
    "ftr.srv.5": "Contenu IA Gen",
    "ftr.srv.6": "IA Intelligence",
    "ftr.srv.7": "Design UI/UX",
    "ftr.srv.8": "SEO Technique",
    
    "ftr.nav.1": "À propos",
    "ftr.nav.2": "Services",
    "ftr.nav.3": "Témoignages",
    "ftr.nav.4": "Contact",

    "ftr.cnt.1": "Démarrer un Projet",
    "ftr.cnt.2": "Réserver une Démo",
    
    "ftr.pol.1": "Politique de Confidentialité",
    "ftr.pol.2": "Conditions d'Utilisation",
    "ftr.pol.3": "Paramètres des Cookies",
    "ftr.copy": "© 2026 Softcr8ors. Tous droits réservés."
  },
  zh: {
    "ind.1.name": "医疗保健",
    "ind.1.desc": "用于现代患者护理的先进数字健康生态系统和人工智能驱动的诊断。",
    "ind.2.name": "电子商务",
    "ind.2.desc": "具有自主智能和个性化购物的下一代零售解决方案。",
    "ind.3.name": "教育",
    "ind.3.desc": "由交互式和沉浸式技术提供支持的可扩展的全球学习平台。",
    "ind.4.name": "房地产",
    "ind.4.desc": "用于未来开发的沉浸式房地产解决方案和建筑可视化。",
    "ind.5.name": "金融",
    "ind.5.desc": "安全、数据驱动的经济框架和面向全球市场的金融科技创新。",
    "ind.6.name": "物流",
    "ind.6.desc": "通过神经网络集成优化供应链和自动配送系统。",
    
    "tst.1.text": "Softcr8ors 从头开始构建了我们整个电子商务平台。设计令人惊叹，自推出以来转化率提高了 40%。",
    "tst.1.role": "首席执行官, LuxeCart",
    "tst.2.text": "他们的 UI/UX 团队改变了我们应用程序的体验。重新设计后的第一个月内，用户保留率翻了一番。",
    "tst.2.role": "产品负责人, Evergreen",
    "tst.3.text": "他们为我们创造的品牌标识令人难以置信。我们收到了客户和合作伙伴的很多赞美。",
    "tst.3.role": "创始人, Atlas Studios",
    "tst.4.text": "视频制作质量确实是电影级别的。我们的品牌卷轴在第一周就获得了超过 50 万次的观看。",
    "tst.4.role": "首席营销官, NovaBrands",
    "tst.5.text": "他们提前交付了我们的定制 CRM 软件，并且运行完美。强烈推荐该团队。",
    "tst.5.role": "首席运营官, TechFlow",
    "tst.6.text": "Softcr8ors 重新设计了我们的整个数字形象。该网站快速、美观，并且转化率前所未有。",
    "tst.6.role": "总监, Q Global",
    "tst.7.text": "专业、有创意、技术精湛。他们在 8 周内将我们粗糙的想法变成了完善的移动应用程序。",
    "tst.7.role": "联合创始人, Appify",
    "tst.8.text": "我们合作过的最好的机构。他们的音频和视频编辑将我们的内容提升到了一个全新的专业水平。",
    "tst.8.role": "营销主管, CreatorHub",

    "srv.1": "远程 IT 资源",
    "srv.2": "定制软件开发",
    "srv.3": "Web 开发",
    "srv.4": "移动应用开发",
    "srv.5": "增强现实 / 虚拟现实",
    "srv.6": "游戏",
    "srv.7": "网络安全",
    "srv.8": "其他 IT 服务",

    "team.1.role": "Python AI 工程师",
    "team.2.role": "MERN Stack 开发人员",
    "team.3.role": "Next.js 开发人员",
    "team.4.role": "WordPress 开发人员",
    "team.5.role": "业务拓展开发人员",
    "team.6.role": "UI/UX 设计师",
    "team.7.role": "全栈开发人员",

    "ftr.desc": "Softcr8ors 通过最先进的 Web 工程、定制软件解决方案和生产级 AI 平台为快速发展的公司提供支持。",
    "ftr.srv.1": "Web 工程",
    "ftr.srv.2": "定制软件",
    "ftr.srv.3": "移动创新",
    "ftr.srv.4": "SaaS 平台",
    "ftr.srv.5": "Gen AI 内容",
    "ftr.srv.6": "智能 AI",
    "ftr.srv.7": "UI/UX 设计",
    "ftr.srv.8": "技术 SEO",
    
    "ftr.nav.1": "关于",
    "ftr.nav.2": "服务",
    "ftr.nav.3": "感言",
    "ftr.nav.4": "联系",

    "ftr.cnt.1": "开始一个项目",
    "ftr.cnt.2": "预订演示",
    
    "ftr.pol.1": "隐私政策",
    "ftr.pol.2": "服务条款",
    "ftr.pol.3": "Cookie 设置",
    "ftr.copy": "© 2026 Softcr8ors。保留所有权利。"
  },
  hi: {
    "ind.1.name": "स्वास्थ्य देखभाल",
    "ind.1.desc": "आधुनिक रोगी देखभाल के लिए उन्नत डिजिटल स्वास्थ्य पारिस्थितिकी तंत्र और एआई-संचालित निदान।",
    "ind.2.name": "ई-कॉमर्स",
    "ind.2.desc": "स्वायत्त बुद्धि और व्यक्तिगत खरीदारी के साथ अगली पीढ़ी के खुदरा समाधान।",
    "ind.3.name": "शिक्षा",
    "ind.3.desc": "वैश्विक शिक्षा के लिए स्केलेबल प्लेटफॉर्म, इंटरैक्टिव और इमर्सिव प्रौद्योगिकियों द्वारा संचालित।",
    "ind.4.name": "रियल एस्टेट",
    "ind.4.desc": "भविष्य के लिए तैयार विकास के लिए इमर्सिव संपत्ति समाधान और स्थापत्य दृश्य।",
    "ind.5.name": "वित्त",
    "ind.5.desc": "वैश्विक बाजारों के लिए सुरक्षित, डेटा-संचालित आर्थिक ढांचे और फिनटेक नवाचार।",
    "ind.6.name": "रसद",
    "ind.6.desc": "न्यूरल नेटवर्क एकीकरण के माध्यम से अनुकूलित आपूर्ति श्रृंखला और स्वायत्त वितरण प्रणाली।",
    
    "tst.1.text": "Softcr8ors ने खरोंच से हमारा पूरा ई-कॉमर्स प्लेटफॉर्म बनाया। डिजाइन शानदार है और लॉन्च के बाद से रूपांतरण 40% बढ़ गए हैं।",
    "tst.1.role": "सीईओ, LuxeCart",
    "tst.2.text": "उनकी UI/UX टीम ने हमारे ऐप के अनुभव को बदल दिया। पुनर्रचना के बाद पहले महीने के भीतर उपयोगकर्ता प्रतिधारण दोगुना हो गया।",
    "tst.2.role": "उत्पाद लीड, Evergreen",
    "tst.3.text": "उन्होंने हमारे लिए जो ब्रांड पहचान बनाई वह अविश्वसनीय है। हमें ग्राहकों और भागीदारों से बहुत सारी तारीफें मिली हैं।",
    "tst.3.role": "संस्थापक, Atlas Studios",
    "tst.4.text": "वीडियो उत्पादन गुणवत्ता वास्तव में सिनेमाई है। हमारी ब्रांड रील ने पहले सप्ताह में 500K से अधिक दृश्य उत्पन्न किए।",
    "tst.4.role": "सीएमओ, NovaBrands",
    "tst.5.text": "उन्होंने हमारे कस्टम CRM सॉफ़्टवेयर को समय से पहले डिलीवर किया और यह त्रुटिहीन रूप से काम करता है। मैं टीम की अत्यधिक अनुशंसा करता हूं।",
    "tst.5.role": "सीओओ, TechFlow",
    "tst.6.text": "Softcr8ors ने हमारी पूरी डिजिटल उपस्थिति को फिर से डिज़ाइन किया। वेबसाइट तेज़, सुंदर है, और पहले की तरह परिवर्तित होती है।",
    "tst.6.role": "निदेशक, Q Global",
    "tst.7.text": "पेशेवर, रचनात्मक और तकनीकी रूप से शानदार। उन्होंने 8 हफ्तों में हमारे मोटे विचारों को एक पॉलिश किए गए मोबाइल ऐप में बदल दिया।",
    "tst.7.role": "सह-संस्थापक, Appify",
    "tst.8.text": "सबसे अच्छी एजेंसी जिसके साथ हमने काम किया है। उनके ऑडियो और वीडियो संपादन ने हमारी सामग्री को एक नए पेशेवर स्तर तक बढ़ा दिया है।",
    "tst.8.role": "मार्केटिंग प्रमुख, CreatorHub",

    "srv.1": "रिमोट आईटी संसाधन",
    "srv.2": "कस्टम सॉफ्टवेयर विकास",
    "srv.3": "वेब विकास",
    "srv.4": "मोबाइल ऐप विकास",
    "srv.5": "एआर / वीआर",
    "srv.6": "गेमिंग",
    "srv.7": "साइबर सुरक्षा",
    "srv.8": "अन्य आईटी सेवाएं",

    "team.1.role": "पायथन एआई इंजीनियर",
    "team.2.role": "MERN स्टैक डेवलपर",
    "team.3.role": "Next.js डेवलपर",
    "team.4.role": "वर्डप्रेस डेवलपर",
    "team.5.role": "व्यापार डेवलपर",
    "team.6.role": "UI/UX डिज़ाइनर",
    "team.7.role": "फुल स्टैक डेवलपर",

    "ftr.desc": "Softcr8ors तेजी से बढ़ने वाली कंपनियों को अत्याधुनिक वेब इंजीनियरिंग, कस्टम सॉफ्टवेयर समाधान और उत्पादन के लिए तैयार एआई प्लेटफॉर्म के साथ सशक्त बनाता है।",
    "ftr.srv.1": "वेब इंजीनियरिंग",
    "ftr.srv.2": "कस्टम सॉफ्टवेयर",
    "ftr.srv.3": "मोबाइल इनोवेशन",
    "ftr.srv.4": "SaaS प्लेटफॉर्म",
    "ftr.srv.5": "जेन एआई सामग्री",
    "ftr.srv.6": "इंटेलिजेंस एआई",
    "ftr.srv.7": "UI/UX डिज़ाइन",
    "ftr.srv.8": "तकनीकी एसईओ",
    
    "ftr.nav.1": "के बारे में",
    "ftr.nav.2": "सेवाएं",
    "ftr.nav.3": "प्रशंसापत्र",
    "ftr.nav.4": "संपर्क करें",

    "ftr.cnt.1": "एक प्रोजेक्ट शुरू करें",
    "ftr.cnt.2": "एक डेमो बुक करें",
    
    "ftr.pol.1": "गोपनीयता नीति",
    "ftr.pol.2": "सेवा की शर्तें",
    "ftr.pol.3": "कुकीज़ सेटिंग्स",
    "ftr.copy": "© 2026 Softcr8ors। सर्वाधिकार सुरक्षित।"
  }
};
